In [8]:
import torch

token_embeddings = torch.tensor([
    [1.0, 2.0, 3.0],   # token 1
    [4.0, 5.0, 6.0],   # token 2
    [7.0, 8.0, 9.0],   # token 3
    [10.0, 11.0, 12.0] # token 4
])
attention_mask = torch.tensor([1, 1, 0, 0])  

In [9]:
token_embeddings.size()

torch.Size([4, 3])

In [20]:
explanded_attention_mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

In [22]:
masked_embeddings = token_embeddings * explanded_attention_mask

In [23]:
masked_embeddings

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
sum_embeddings = torch.sum(masked_embeddings,1)

In [31]:
explanded_attention_mask.sum(1)

tensor([3., 3., 0., 0.])

In [33]:
sum_mask = torch.clamp(explanded_attention_mask.sum(1), min=1e-9)

In [34]:
sum_embeddings / sum_mask

tensor([2., 5., 0., 0.])

In [35]:

sentence_embedding = sum_embeddings / sum_mask
sentence_embedding.squeeze()

tensor([2., 5., 0., 0.])